### PR TITLE
make save and cancel buttons stick

### PR DESCRIPTION
**Pull request by mutebironald**
## What is the Purpose?
Briefly describe what the PR addresses
 - [x] make save and cancel buttons stick
## What was the approach?
Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?
State some additional info if any. For instance running `install` or setting some environment variable(s)

## Mentions?
Mention persons you'd like to review this PR
@andrewtpham @michaelbukachi 
## Issue(s) affected?
List of issues addressed by this PR.

### CODE REVIEW

**Comment by mutebironald** [comment]
Note, the Dim profile viewer is not yet implemented.

**Comment by andrewtpham** [comment]
@mutebironald I've gone ahead and updated the issue to only be for making thee buttons stick and move the dimming issue to a separate ticket #146

**Comment by mutebironald** [comment]
> @mutebironald I've gone ahead and updated the issue to only be for making thee buttons stick and move the dimming issue to a separate ticket #146

Alright @andrewtpham

**Comment by andrewtpham** [comment]
Hi @mutebironald In preview it seems the buttons are only sticky to an extent. Is there anyway we can make it stick like the profile drawer on the right side? Note that when you minimize very small the workspace cards become scrollable. Maybe we can do this with the add workspace form?
image

**Comment by mutebironald** [comment]
> Hi @mutebironald In preview it seems the buttons are only sticky to an extent. Is there anyway we can make it stick like the profile drawer on the right side? Note that when you minimize very small the workspace cards become scrollable. Maybe we can do this with the add workspace form?
> image

This seems to be as a result of the error message pushing the other elements further down.  Let me add a scroll to it though.

**Pull request merged**
