### PR TITLE
ISS-#197: Prevent page refresh on pressing enter button

### LINKED ISSUE #197: Forgot password: pressing enter refreshes page instead of submitting email
**Current behavior**
On forgot password page, when user presses 'enter button instead of clicking the 'send reset password' button, the page refreshes instead of sending reset email

**To Reproduce**
1. Go to Forgot password page
2. User adds email address
3. User presses 'enter', instead of clicking on the button

**Expected behavior**
On forgot password page, when user presses 'enter button instead of clicking the 'send reset password' button, the page submits the email and sends reset password link

### PR DESCRIPTION
**Pull request by mutebironald**
## What is the Purpose?
Briefly describe what the PR addresses

## What was the approach?
Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?
State some additional info if any. For instance running `install` or setting some environment variable(s)

## Mentions?
Mention persons you'd like to review this PR

## Issue(s) affected?
List of issues addressed by this PR. 
Resolve #197

### CODE REVIEW

**Comment by mutebironald** [comment]
I have prevented page refresh on enter press. Note that single input elements have this default behaviour. A user will therefore only submit via the button.

**Comment by ninetteadhikari** [comment]
@mutebironald did you close this PR by mistake? or are you making any changes?

**Comment by mutebironald** [comment]
Had closed it to make a few changes. You can reopen it @ninetteadhikari

**Comment by ninetteadhikari** [comment]
I can't seem to open it @mutebironald 😕  can you please try opening it? otherwise just create a new PR. 
you can also try converting it to 'Draft' to make changes instead of closing it 🙂

**Pull request closed without merging**
