### PR TITLE
Add registration page

### PR DESCRIPTION
**Pull request by michaelbukachi**
## What is the Purpose?
Styled up login page
Add registration page and styled it up

## What was the approach?
Added custom styling to login page
Add registration component

## Are there any concerns to addressed further before or after merging this PR?
State some additional info if any. For instance running `install` or setting some environment variable(s)
- Placeholders are invincible
- Password validation is missing a couple of rules
- Inputs don't match the design
- Better handling of error responses from the API is required.

## Mentions?
Mention persons you'd like to review this PR
@andrewtpham @nasirhjafri @odenypeter @ninetteadhikari 

## Issue(s) affected?
#27 #4

### CODE REVIEW

**Comment by andrewtpham** [comment]
@michaelbukachi Wow, it looks great! And the element icons look great and are fine for now 😉

I noticed a few things in case its not too much trouble to adjust:
- On the log in page, when the `This field is required` message is displayed, there seems to be a line break where it is displayed:
Screen Shot 2020-04-19 at 12 02 28 AM
- On the Create an account page, there seems to be a line break between `Confirm Password` label:
Screen Shot 2020-04-19 at 12 04 11 AM
- On the Create an account page, can we align the input fields to be the same height and width for consistency. We can make the input fields the same length as the `Password` and `Confirm Password` fields? It looks like these fields are: 194 x 40:
Screen Shot 2020-04-19 at 12 22 58 AM

**Comment by odenypeter** [comment]
@michaelbukachi @andrewtpham 
Let me know when this can be merged, I need it for my work.

**Comment by michaelbukachi** [comment]
> @michaelbukachi @andrewtpham
> Let me know when this can be merged, I need it for my work.

@andrewtpham you can now merge the changes.

**Comment by nasirhjafri** [comment]
> @michaelbukachi Wow, it looks great! And the element icons look great and are fine for now 😉
> 
> I noticed a few things in case its not too much trouble to adjust:
> 
> * On the log in page, when the `This field is required` message is displayed, there seems to be a line break where it is displayed:
> 
> Screen Shot 2020-04-19 at 12 02 28 AM
> 
> - On the Create an account page, there seems to be a line break between `Confirm Password` label:
> Screen Shot 2020-04-19 at 12 04 11 AM
> 
> - On the Create an account page, can we align the input fields to be the same height and width for consistency. We can make the input fields the same length as the `Password` and `Confirm Password` fields? It looks like these fields are: 194 x 40:
> Screen Shot 2020-04-19 at 12 22 58 AM
> 
> - On the Create an account page, can we provide more spacing between the two columns of input fields so that `Confirm Password` label can be on a single line? Also the 2nd column should be `right-aligned` to the input fields. See screenshot:
> Screen Shot 2020-04-19 at 12 36 27 AM

@michaelbukachi I still see these issues.

**Comment by michaelbukachi** [comment]
> > @michaelbukachi Wow, it looks great! And the element icons look great and are fine for now wink
> > I noticed a few things in case its not too much trouble to adjust:
> > 
> > * On the log in page, when the `This field is required` message is displayed, there seems to be a line break where it is displayed:
> > 
> > Screen Shot 2020-04-19 at 12 02 28 AM
> > 
> > * On the Create an account page, there seems to be a line break between `Confirm Password` label:
> > 
> > Screen Shot 2020-04-19 at 12 04 11 AM
> > 
> > * On the Create an account page, can we align the input fields to be the same height and width for consistency. We can make the input fields the same length as the `Password` and `Confirm Password` fields? It looks like these fields are: 194 x 40:
> > 
> > Screen Shot 2020-04-19 at 12 22 58 AM
> > 
> > * On the Create an account page, can we provide more spacing between the two columns of input fields so that `Confirm Password` label can be on a single line? Also the 2nd column should be `right-aligned` to the input fields. See screenshot:
> > 
> > Screen Shot 2020-04-19 at 12 36 27 AM
> 
> @michaelbukachi I still see these issues.

I'll do a new PR for this.

**Pull request merged**
