### PR TITLE
Map styling

### PR DESCRIPTION
**Pull request by andrewtpham**
## What is the Purpose?
- added `CollapseNav` to Map page
- added map styling

## What was the approach?
Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?
State some additional info if any. For instance running `install` or setting some environment variable(s)

## Mentions?
@michaelbukachi @odenypeter @ninetteadhikari 

## Issue(s) affected?
List of issues addressed by this PR.

### CODE REVIEW

**Comment by michaelbukachi** [comment]
Nice! We need to enforce text wrapping though.
screenshot_20200520230634

**Comment by andrewtpham** [comment]
> Nice! We need to enforce text wrapping though.
> screenshot_20200520230634

Hey @michaelbukachi I've been trying to fixing the text wrapping issue but having no luck. Any ideas? So far, I've tried `word-wrap: break-word;` as well as `overflow-wrap: break-word;` in the CSS but it doesnt seem to have an effect. I thought it might have something to do with the table name not having spaces but it seems like this CSS property should still work in the use case. cc: @lupyana in case you have some ideas? Thanks

**Comment by michaelbukachi** [comment]
> > Nice! We need to enforce text wrapping though.
> > screenshot_20200520230634
> 
> Hey @michaelbukachi I've been trying to fixing the text wrapping issue but having no luck. Any ideas? So far, I've tried `word-wrap: break-word;` as well as `overflow-wrap: break-word;` in the CSS but it doesnt seem to have an effect. I thought it might have something to do with the table name not having spaces but it seems like this CSS property should still work in the use case. cc: @lupyana in case you have some ideas? Thanks

Hey. Figured it out. Just add the following snippet to maps css and it should be good
```
  .maps {
    .el-menu-item {
      height: auto;
      white-space: normal;
      word-break: break-word;
    }
  }
```
Though I think this should be added in the library

**Comment by andrewtpham** [comment]
> > > Nice! We need to enforce text wrapping though.
> > > screenshot_20200520230634
> > 
> > 
> > Hey @michaelbukachi I've been trying to fixing the text wrapping issue but having no luck. Any ideas? So far, I've tried `word-wrap: break-word;` as well as `overflow-wrap: break-word;` in the CSS but it doesnt seem to have an effect. I thought it might have something to do with the table name not having spaces but it seems like this CSS property should still work in the use case. cc: @lupyana in case you have some ideas? Thanks
> 
> Hey. Figured it out. Just add the following snippet to maps css and it should be good
> 
> ```
>   .maps {
>     .el-menu-item {
>       height: auto;
>       white-space: normal;
>       word-break: break-word;
>     }
>   }
> ```
> 
> Though I think this should be added in the library

Ah ha! It was this that I was missing! Thanks so much @michaelbukachi. Someday I'll be a CSS guru like you 🙇 
```
      height: auto;
      white-space: normal;
```

**Comment by andrewtpham** [comment]
@michaelbukachi I've been trying to add it to the `ui components` but its creating a lot of other issues. Is it okay if I leave it in the FE for now?

**Comment by michaelbukachi** [comment]
> @michaelbukachi I've been trying to add it to the `ui components` but its creating a lot of other issues. Is it okay if I leave it in the FE for now?

Sure, no problem. I'll try to address it when I touch on the input components.

**Pull request merged**
