### PR TITLE
Cypress setup so as to write FE automated tests

### PR DESCRIPTION
**Pull request by sannleen**
## What is the Purpose?
Setting up cypress so that we can start writing front end automated test cases

## What was the approach?
Use [vue cypress plugin](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-e2e-cypress)

## Are there any concerns to addressed further before or after merging this PR?
none

## Mentions?
@michaelbukachi @andrewtpham @odenypeter 

## Issue(s) affected?
https://github.com/hikaya-io/dots-frontend/issues/91

### CODE REVIEW

**Comment by sannleen** [comment]
> Nicely done. Is it possible to add the necessary commands to github actions to run the tests?

Yes, that's the plan, once I start adding testes we can set it up so that the test also run as part of the CI process.
@michaelbukachi please help me resolve the conflict with the `bluebird@3.5.0` package

**Comment by michaelbukachi** [comment]
@andrewtpham Can we merge this? It contains the code for the navbar fix.

**Comment by andrewtpham** [comment]
Yes, we can merge. Is it ok the verve deployment failed?

**Comment by michaelbukachi** [comment]
@andrewtpham I've fixed it.

**Pull request merged**
