### PR TITLE
ISS-#197: Prevent page refresh on pressing enter button

### LINKED ISSUE #197: Forgot password: pressing enter refreshes page instead of submitting email
**Current behavior**
On forgot password page, when user presses 'enter button instead of clicking the 'send reset password' button, the page refreshes instead of sending reset email

**To Reproduce**
1. Go to Forgot password page
2. User adds email address
3. User presses 'enter', instead of clicking on the button

**Expected behavior**
On forgot password page, when user presses 'enter button instead of clicking the 'send reset password' button, the page submits the email and sends reset password link

### PR DESCRIPTION
**Pull request by mutebironald**
## What is the Purpose?
Briefly describe what the PR addresses
- [x] Prevents page refresh on pressing enter
## What was the approach?
Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?
State some additional info if any. For instance running `install` or setting some environment variable(s)

## Mentions?
Mention persons you'd like to review this PR

## Issue(s) affected?
List of issues addressed by this PR. 
Resolve #197

### CODE REVIEW

**Comment by mutebironald** [comment]
I have prevented page refresh on enter press. Note that single input elements have this default behaviour. A user will therefore only submit via the button.

**Comment by andrewtpham** [comment]
@mutebironald thanks for taking this one on! Looking at the acceptance criteria, we did not to refresh the page upon hitting `enter` on the keyboard but instead when a user hits `enter` on the keyboard it should submit for sending the email for reset password.

**Comment by mutebironald** [comment]
> @mutebironald thanks for taking this one on! Looking at the acceptance criteria, we did not to refresh the page upon hitting `enter` on the keyboard but instead when a user hits `enter` on the keyboard it should submit for sending the email for reset password.

https://github.com/hikaya-io/dots-frontend/pull/211#issuecomment-648257053 . for a single input element, allowing a submit via the enter key will lead to a page refresh like i have pointed out in the comment attached

**Comment by mutebironald** [comment]
> @mutebironald thanks for taking this one on! Looking at the acceptance criteria, we did not to refresh the page upon hitting `enter` on the keyboard but instead when a user hits `enter` on the keyboard it should submit for sending the email for reset password.

@andrewtpham This is now fixed.

**Pull request merged**
